### Reload: tmux source-file ~/.tmux.conf ###

unbind C-b
set -g prefix C-g
bind C-g send-prefix

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind -r H resize-pane -L 5
bind -r J resize-pane -D 2
bind -r K resize-pane -U 2
bind -r L resize-pane -R 5

set -g default-terminal "xterm-256color"
set -as terminal-overrides ",*:Tc"
set -g mouse on
set -g mode-keys vi

# clipboard command detect
if-shell 'command -v pbcopy >/dev/null 2>&1' \
  'set -g @clipboard "pbcopy"' \
  'if-shell "command -v wl-copy >/dev/null 2>&1" \
    "set -g @clipboard wl-copy" \
    "if-shell \"command -v xclip >/dev/null 2>&1\" \
      \"set -g @clipboard xclip -selection clipboard\" \
      \"set -g @clipboard\""'

# bind (copy-mode-vi)
bind-key -T copy-mode-vi y     send-keys -X copy-pipe-and-cancel "#{@clipboard}"
bind-key -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel "#{@clipboard}"

set -g pane-border-style fg=colour240
set -g pane-active-border-style fg=colour40

